spring.application.name=manju-backend-middleware


# Enable the H2 Console
spring.h2.console.enabled=true

# Set the path to access it (default is /h2-console)
spring.h2.console.path=/h2-console

# This ensures the database persists in memory for the session
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Use 'create' instead of 'update' for one run to force a fresh table
spring.jpa.hibernate.ddl-auto=update